"""empty message

Revision ID: a413791b5d0b
Revises: d434734cea00
Create Date: 2016-02-27 14:22:12.970910

"""

# revision identifiers, used by Alembic.
revision = 'a413791b5d0b'
down_revision = 'd434734cea00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'description')
    ### end Alembic commands ###
